# -
import torch


# +
# ------------------------
# CONFIG
# ------------------------
HIDDEN_DIM = 256
EMBED_DIM = 16
PROJ_DIM = 2
BATCH_SIZE = 1024 #1024
GT_ENRICHMENT = 0.10
GT_POOL_SIZE = 2048
GT_SCORE_INIT = 1.0
GT_SCORE_DECAY = 0.01
GT_SCORE_IN_MEMORY_DECAY = 0.7
GT_SCORE_MIN = 0.01
GT_CLASS_RARITY_ALPHA = .7
GT_SPATIAL_RARITY_ALPHA = 1-GT_CLASS_RARITY_ALPHA
GT_DB_UPDATE_BATCH = 128
GT_DB_UPDATE_INTERVAL = 1.0
GT_POOL_UPDATE_INTERVAL = 5
MEMORY_BANK_SIZE = 1024  # 5000
MEMORY_SAMPLE_SIZE = 256  # 1024  #--- seems pretty big?
NVIEWS = 4
GRID_SIZE = 100  # projection grid
# TEMPORAL_ALPHA = 0.05
# TEMPORAL_LAMBDA = 0.1
# BATCH_BIN_LAMBDA = 0.5
# NEIGHBOR_LAMBDA = 1.0
# INTRA_BIN_LAMBDA = 0.1
# INTER_BIN_LAMBDA = 0.1
# PSEUDO_PRED_LAMBDA=.8

SEMANTIC_COORD_LAMBDA = 1.0
SEMANTIC_EMB_LAMBDA = 10.0
TEMPORAL_ALPHA = 0.05  # unchanged, decay rate is fine
TEMPORAL_LAMBDA = 0.15
BATCH_BIN_LAMBDA = 1.0
NEIGHBOR_LAMBDA = .5 #need t oforce high trustworthyness
INTRA_BIN_LAMBDA = 0.3
PSEUDO_PRED_LAMBDA = 0.0001
PRED_SUP_LAMBDA = 10_000.0
PRED_PSEUDO_LAMBDA = PRED_SUP_LAMBDA * PSEUDO_PRED_LAMBDA
REPULSION_LAMBDA = 0.1
COORD_CONSITENCY_LOSS = 1
COORD_CONTRASTIVE_LOSS = 0
SIMCLR_EMB_LOSS = 100

SPREAD_LOSS = 10.0
MAX_MEAN_LOSS = 10_000.0
PSEUDO_THRESH = 0.9

USE_MASK = True


LOG_ORIGS = True
LOG_EVERY = 100

K_NEIGHBORS = 50 # was 5 -- but i think these should be much higher
EPS = 1e-6
DEVICE = "cuda:1" if torch.cuda.is_available() else "cpu"
NWORKERS_BASE = 32
NWORKERS_ENRICH = 4


PATCH_SIZE = 60  # 64 #this should allow for some local translation
N_CLASS = 5
# Loss selection: 'simclr' or 'swav'
LOSS_TYPE = "swav"

# SwAV-specific defaults
SWAV_PROTOTYPES = 300
SWAV_KMEANS_ITERS = 10
SWAV_SINKHORN_ITERS = 3
SWAV_EPS = 0.05


LOAD_CHECKPOINT = False
TORCH_PROFILE = False # Enable torch profiler (record CPU/CUDA traces to runs/torch_prof)
LOG_EMBEDDINGS_TOSQL = True # Log embeddings to tensorboard

NBATCH_PSEUDO_WARMUP = 50