# docker run -d --name citus_single -p 5432:5432 -e POSTGRES_PASSWORD=password citusdata/citus:14.0

version: '3.8'
services:
  db:
    image: citusdata/citus:14.0
    container_name: citus_single
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"