// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetConfusionMatrixConfusionMatrixGetData, GetConfusionMatrixConfusionMatrixGetErrors, GetConfusionMatrixConfusionMatrixGetResponses, InfoInfoGetData, InfoInfoGetResponses, ServeTileTilesZxyPngGetData, ServeTileTilesZxyPngGetErrors, ServeTileTilesZxyPngGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Info
 */
export const infoInfoGet = <ThrowOnError extends boolean = false>(options?: Options<InfoInfoGetData, ThrowOnError>) => (options?.client ?? client).get<InfoInfoGetResponses, unknown, ThrowOnError>({ url: '/info', ...options });

/**
 * Serve Tile
 */
export const serveTileTilesZXYPngGet = <ThrowOnError extends boolean = false>(options: Options<ServeTileTilesZxyPngGetData, ThrowOnError>) => (options.client ?? client).get<ServeTileTilesZxyPngGetResponses, ServeTileTilesZxyPngGetErrors, ThrowOnError>({ url: '/tiles/{z}/{x}/{y}.png', ...options });

/**
 * Get Confusion Matrix
 */
export const getConfusionMatrixConfusionMatrixGet = <ThrowOnError extends boolean = false>(options: Options<GetConfusionMatrixConfusionMatrixGetData, ThrowOnError>) => (options.client ?? client).get<GetConfusionMatrixConfusionMatrixGetResponses, GetConfusionMatrixConfusionMatrixGetErrors, ThrowOnError>({ url: '/confusion_matrix', ...options });
