// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ConfusionMatrixResponse
 */
export type ConfusionMatrixResponse = {
    /**
     * Gt Labels
     */
    gt_labels: Array<number>;
    /**
     * Pred Labels
     */
    pred_labels: Array<number>;
    /**
     * Matrix
     */
    matrix: Array<Array<number>>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LabelAssignByPolygonRequest
 */
export type LabelAssignByPolygonRequest = {
    /**
     * Polygon
     */
    polygon: {
        [key: string]: unknown;
    };
};

/**
 * LabelAssignResponse
 */
export type LabelAssignResponse = {
    /**
     * Updated
     */
    updated: number;
};

/**
 * LabelClassResponse
 */
export type LabelClassResponse = {
    /**
     * Label Class Id
     */
    label_class_id: number;
    /**
     * Project Id
     */
    project_id: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Color Code
     */
    color_code?: string | null;
    /**
     * Event Ts
     */
    event_ts: string;
};

/**
 * PatchResponse
 */
export type PatchResponse = {
    /**
     * Patch Id
     */
    patch_id: number;
    /**
     * Patch Uid
     */
    patch_uid: string;
    /**
     * Label Class Id
     */
    label_class_id: number;
    /**
     * Image Id
     */
    image_id: number;
    /**
     * Downsample Factor
     */
    downsample_factor: number;
    /**
     * Centroid X
     */
    centroid_x?: number | null;
    /**
     * Centroid Y
     */
    centroid_y?: number | null;
    /**
     * Polygon
     */
    polygon?: string | null;
    /**
     * Embed X
     */
    embed_x?: number | null;
    /**
     * Embed Y
     */
    embed_y?: number | null;
    /**
     * Grid Cell I
     */
    grid_cell_i?: number | null;
    /**
     * Grid Cell J
     */
    grid_cell_j?: number | null;
    /**
     * Pred Label Class Id
     */
    pred_label_class_id?: number | null;
    /**
     * Event Ts
     */
    event_ts?: string | null;
    /**
     * Priority
     */
    priority?: number | null;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Project Name
     */
    project_name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * SumOver
 */
export type SumOver = 'gt' | 'pred';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorldInfo
 */
export type WorldInfo = {
    /**
     * World
     */
    world: {
        [key: string]: unknown;
    };
    /**
     * Osm Zoom Offset
     */
    osm_zoom_offset: number;
    /**
     * Max Level
     */
    max_level: number;
};

export type InfoApiV1ProjectsProjectIdInfoGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/info';
};

export type InfoApiV1ProjectsProjectIdInfoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InfoApiV1ProjectsProjectIdInfoGetError = InfoApiV1ProjectsProjectIdInfoGetErrors[keyof InfoApiV1ProjectsProjectIdInfoGetErrors];

export type InfoApiV1ProjectsProjectIdInfoGetResponses = {
    /**
     * Successful Response
     */
    200: WorldInfo;
};

export type InfoApiV1ProjectsProjectIdInfoGetResponse = InfoApiV1ProjectsProjectIdInfoGetResponses[keyof InfoApiV1ProjectsProjectIdInfoGetResponses];

export type ServeTileApiV1ProjectsProjectIdTilesZxyPngGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Z
         */
        z: number;
        /**
         * X
         */
        x: number;
        /**
         * Y
         */
        y: number;
    };
    query?: {
        sum_over?: SumOver;
        /**
         * Lp
         */
        lp?: Array<string> | null;
    };
    url: '/api/v1/projects/{project_id}/tiles/{z}/{x}/{y}.png';
};

export type ServeTileApiV1ProjectsProjectIdTilesZxyPngGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServeTileApiV1ProjectsProjectIdTilesZxyPngGetError = ServeTileApiV1ProjectsProjectIdTilesZxyPngGetErrors[keyof ServeTileApiV1ProjectsProjectIdTilesZxyPngGetErrors];

export type ServeTileApiV1ProjectsProjectIdTilesZxyPngGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * X Min
         */
        x_min: number;
        /**
         * Y Min
         */
        y_min: number;
        /**
         * X Max
         */
        x_max: number;
        /**
         * Y Max
         */
        y_max: number;
        /**
         * Lp
         */
        lp?: Array<string> | null;
    };
    url: '/api/v1/projects/{project_id}/confusion_matrix';
};

export type GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetError = GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetErrors[keyof GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetErrors];

export type GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetResponses = {
    /**
     * Successful Response
     */
    200: ConfusionMatrixResponse;
};

export type GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetResponse = GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetResponses[keyof GetConfusionMatrixApiV1ProjectsProjectIdConfusionMatrixGetResponses];

export type ListProjectsApiV1ProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type ListProjectsApiV1ProjectsGetResponses = {
    /**
     * Response List Projects Api V1 Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ListProjectsApiV1ProjectsGetResponse = ListProjectsApiV1ProjectsGetResponses[keyof ListProjectsApiV1ProjectsGetResponses];

export type GetProjectApiV1ProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type GetProjectApiV1ProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectApiV1ProjectsProjectIdGetError = GetProjectApiV1ProjectsProjectIdGetErrors[keyof GetProjectApiV1ProjectsProjectIdGetErrors];

export type GetProjectApiV1ProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectApiV1ProjectsProjectIdGetResponse = GetProjectApiV1ProjectsProjectIdGetResponses[keyof GetProjectApiV1ProjectsProjectIdGetResponses];

export type ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/label_classes/';
};

export type ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetError = ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetErrors[keyof ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetErrors];

export type ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetResponses = {
    /**
     * Response List Label Classes Api V1 Projects  Project Id  Label Classes  Get
     *
     * Successful Response
     */
    200: Array<LabelClassResponse>;
};

export type ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetResponse = ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetResponses[keyof ListLabelClassesApiV1ProjectsProjectIdLabelClassesGetResponses];

export type GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Label Class Id
         */
        label_class_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/label_classes/{label_class_id}';
};

export type GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetError = GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetErrors[keyof GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetErrors];

export type GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetResponses = {
    /**
     * Successful Response
     */
    200: LabelClassResponse;
};

export type GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetResponse = GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetResponses[keyof GetLabelClassApiV1ProjectsProjectIdLabelClassesLabelClassIdGetResponses];

export type ListPatchesApiV1ProjectsProjectIdPatchesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Cursor
         *
         * Keyset cursor: last seen patch_id (exclusive lower bound)
         */
        cursor?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * X Min
         */
        x_min?: number | null;
        /**
         * Y Min
         */
        y_min?: number | null;
        /**
         * X Max
         */
        x_max?: number | null;
        /**
         * Y Max
         */
        y_max?: number | null;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
    };
    url: '/api/v1/projects/{project_id}/patches/';
};

export type ListPatchesApiV1ProjectsProjectIdPatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPatchesApiV1ProjectsProjectIdPatchesGetError = ListPatchesApiV1ProjectsProjectIdPatchesGetErrors[keyof ListPatchesApiV1ProjectsProjectIdPatchesGetErrors];

export type ListPatchesApiV1ProjectsProjectIdPatchesGetResponses = {
    /**
     * Response List Patches Api V1 Projects  Project Id  Patches  Get
     *
     * Successful Response
     */
    200: Array<PatchResponse>;
};

export type ListPatchesApiV1ProjectsProjectIdPatchesGetResponse = ListPatchesApiV1ProjectsProjectIdPatchesGetResponses[keyof ListPatchesApiV1ProjectsProjectIdPatchesGetResponses];

export type AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * Patch Ids
         *
         * Patch IDs to relabel
         */
        patch_ids: Array<number>;
        /**
         * Label Class Id
         *
         * Ground-truth label class to assign
         */
        label_class_id: number;
    };
    url: '/api/v1/projects/{project_id}/patches/';
};

export type AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostError = AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostErrors[keyof AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostErrors];

export type AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostResponses = {
    /**
     * Successful Response
     */
    200: LabelAssignResponse;
};

export type AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostResponse = AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostResponses[keyof AssignLabelsByIdsApiV1ProjectsProjectIdPatchesPostResponses];

export type GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Patch Id
         */
        patch_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/patches/{patch_id}';
};

export type GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetError = GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetErrors[keyof GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetErrors];

export type GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetResponses = {
    /**
     * Successful Response
     */
    200: PatchResponse;
};

export type GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetResponse = GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetResponses[keyof GetPatchApiV1ProjectsProjectIdPatchesPatchIdGetResponses];

export type GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Patch Id
         */
        patch_id: number;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/patches/{patch_id}/image';
};

export type GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetError = GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetErrors[keyof GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetErrors];

export type GetPatchImageApiV1ProjectsProjectIdPatchesPatchIdImageGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostData = {
    body: LabelAssignByPolygonRequest;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * Label Class Id
         *
         * Ground-truth label class to assign
         */
        label_class_id: number;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
    };
    url: '/api/v1/projects/{project_id}/patches/polygonassign';
};

export type AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostError = AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostErrors[keyof AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostErrors];

export type AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostResponses = {
    /**
     * Successful Response
     */
    200: LabelAssignResponse;
};

export type AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostResponse = AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostResponses[keyof AssignLabelsByPolygonApiV1ProjectsProjectIdPatchesPolygonassignPostResponses];

export type SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * Xmin
         */
        xmin: number;
        /**
         * Xmax
         */
        xmax: number;
        /**
         * Ymin
         */
        ymin: number;
        /**
         * Ymax
         */
        ymax: number;
        /**
         * Num Samples
         */
        num_samples?: number;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
        /**
         * Patch Query Range
         *
         * Range in grid cells around each query point for patch sampling
         */
        patch_query_range?: number;
    };
    url: '/api/v1/projects/{project_id}/sample/by-bbox/patches/';
};

export type SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetError = SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetErrors[keyof SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetErrors];

export type SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetResponses = {
    /**
     * Response Sample Patches By Bbox Api V1 Projects  Project Id  Sample By Bbox Patches  Get
     *
     * Successful Response
     */
    200: Array<PatchResponse>;
};

export type SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetResponse = SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetResponses[keyof SamplePatchesByBboxApiV1ProjectsProjectIdSampleByBboxPatchesGetResponses];

export type SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * X
         */
        x: number;
        /**
         * Y
         */
        y: number;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
        /**
         * Patch Query Range
         *
         * Range in grid cells around the query point for patch sampling
         */
        patch_query_range?: number;
    };
    url: '/api/v1/projects/{project_id}/sample/by-point/patches/';
};

export type SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetError = SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetErrors[keyof SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetErrors];

export type SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetResponses = {
    /**
     * Response Sample Patches By Point Api V1 Projects  Project Id  Sample By Point Patches  Get
     *
     * Successful Response
     */
    200: Array<PatchResponse>;
};

export type SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetResponse = SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetResponses[keyof SamplePatchesByPointApiV1ProjectsProjectIdSampleByPointPatchesGetResponses];
