// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

/**
 * Body_process_upload_csv
 */
export type BodyProcessUploadCsv = {
    /**
     * Csv File
     */
    csv_file: Blob | File;
};

/**
 * Body_upload_images
 */
export type BodyUploadImages = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_upload_masks
 */
export type BodyUploadMasks = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_upload_patch_csv
 */
export type BodyUploadPatchCsv = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_validate_upload_image_csv
 */
export type BodyValidateUploadImageCsv = {
    /**
     * Csv File
     */
    csv_file: Blob | File;
};

/**
 * ConfusionMatrixResponse
 */
export type ConfusionMatrixResponse = {
    /**
     * Gt Labels
     */
    gt_labels: Array<number>;
    /**
     * Pred Labels
     */
    pred_labels: Array<number>;
    /**
     * Matrix
     */
    matrix: Array<Array<number>>;
};

/**
 * ExportRequest
 *
 * Request body for starting a patch CSV export.
 */
export type ExportRequest = {
    /**
     * Image Ids
     */
    image_ids: Array<number>;
    /**
     * Label Class Ids
     */
    label_class_ids?: Array<number>;
};

/**
 * ExportResponse
 *
 * Response from export_patch_csv endpoint.
 */
export type ExportResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Manifest Urls
     */
    manifest_urls: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageResponse
 */
export type ImageResponse = {
    /**
     * Image Id
     */
    image_id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Image Path
     */
    image_path: string;
    /**
     * Base Mag
     */
    base_mag: number;
    /**
     * Base Width
     */
    base_width: number;
    /**
     * Base Height
     */
    base_height: number;
    /**
     * Deepzoom Tilesize
     */
    deepzoom_tilesize: number;
};

/**
 * ImageStatsResponse
 */
export type ImageStatsResponse = {
    /**
     * Total Patches
     */
    total_patches: number | null;
    /**
     * Labeled Patches
     */
    labeled_patches: number | null;
};

/**
 * LabelAssignByPolygonRequest
 */
export type LabelAssignByPolygonRequest = {
    /**
     * Polygon
     */
    polygon: {
        [key: string]: unknown;
    };
};

/**
 * LabelAssignResponse
 */
export type LabelAssignResponse = {
    /**
     * Updated
     */
    updated: number;
};

/**
 * LabelClassResponse
 */
export type LabelClassResponse = {
    /**
     * Label Class Id
     */
    label_class_id: number;
    /**
     * Project Id
     */
    project_id: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Color Code
     */
    color_code?: string | null;
    /**
     * Event Ts
     */
    event_ts: string;
};

/**
 * OpenSessionResponse
 */
export type OpenSessionResponse = {
    /**
     * Session
     */
    session: string;
};

/**
 * PatchResponse
 */
export type PatchResponse = {
    /**
     * Patch Id
     */
    patch_id: number;
    /**
     * Patch Uid
     */
    patch_uid: string;
    /**
     * Label Class Id
     */
    label_class_id: number;
    /**
     * Image Id
     */
    image_id: number;
    /**
     * Downsample Factor
     */
    downsample_factor: number;
    /**
     * Centroid X
     */
    centroid_x?: number | null;
    /**
     * Centroid Y
     */
    centroid_y?: number | null;
    /**
     * Polygon
     */
    polygon?: string | null;
    /**
     * Embed X
     */
    embed_x?: number | null;
    /**
     * Embed Y
     */
    embed_y?: number | null;
    /**
     * Grid Cell I
     */
    grid_cell_i?: number | null;
    /**
     * Grid Cell J
     */
    grid_cell_j?: number | null;
    /**
     * Pred Label Class Id
     */
    pred_label_class_id?: number | null;
    /**
     * Event Ts
     */
    event_ts?: string | null;
    /**
     * Priority
     */
    priority?: number | null;
};

/**
 * ProcessCsvResponse
 */
export type ProcessCsvResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ProcessRequest
 */
export type ProcessRequest = {
    /**
     * Paths
     */
    paths: Array<ProcessRow>;
};

/**
 * ProcessResponse
 */
export type ProcessResponse = {
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ProcessRow
 */
export type ProcessRow = {
    /**
     * Image
     */
    image: string | null;
    /**
     * Mask
     */
    mask: string | null;
    /**
     * Csv
     */
    csv: string | null;
    /**
     * Base Mag
     */
    base_mag?: number | null;
};

/**
 * ProjectResponse
 */
export type ProjectResponse = {
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Project Name
     */
    project_name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Creation Ts
     */
    creation_ts?: string | null;
    /**
     * Total Patches
     */
    total_patches?: number | null;
};

/**
 * ProjectStatsResponse
 */
export type ProjectStatsResponse = {
    /**
     * Num Images
     */
    num_images: number;
    /**
     * Patch Size
     */
    patch_size: number | null;
    /**
     * Num Label Classes
     */
    num_label_classes: number;
    /**
     * Total Objects
     */
    total_objects: number;
    /**
     * Labeled Count
     */
    labeled_count: number;
    /**
     * Creation Date
     */
    creation_date: string | null;
    /**
     * Modification Date
     */
    modification_date: string | null;
};

/**
 * ReviewRow
 */
export type ReviewRow = {
    /**
     * Image
     */
    image: string | null;
    /**
     * Mask
     */
    mask: string | null;
    /**
     * Csv
     */
    csv: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Base Mag
     */
    base_mag?: number | null;
};

/**
 * SettingResponse
 */
export type SettingResponse = {
    /**
     * Setting Id
     */
    setting_id: number;
    /**
     * Project Id
     */
    project_id: number | null;
    /**
     * Setting Key
     */
    setting_key: string;
    /**
     * Setting Value
     */
    setting_value: string;
    /**
     * Default Value
     */
    default_value: string;
    /**
     * Setting Type
     */
    setting_type: string;
    /**
     * Allowed Values
     */
    allowed_values: string | null;
    /**
     * Disabled
     */
    disabled: boolean;
};

/**
 * SumOver
 */
export type SumOver = 'gt' | 'pred';

/**
 * UploadFilesResponse
 */
export type UploadFilesResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidateRequest
 *
 * Unified validation request — all sources are globbed from the session temp dir.
 */
export type ValidateRequest = {
    /**
     * Image Folder
     */
    image_folder?: string | null;
    /**
     * Mask Folder
     */
    mask_folder?: string | null;
    /**
     * Patch Csv Folder
     */
    patch_csv_folder?: string | null;
};

/**
 * ValidateResponse
 */
export type ValidateResponse = {
    /**
     * Paths
     */
    paths: Array<ReviewRow>;
    /**
     * Errors
     */
    errors: number;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorldInfo
 */
export type WorldInfo = {
    /**
     * World
     */
    world: {
        [key: string]: unknown;
    };
    /**
     * Osm Zoom Offset
     */
    osm_zoom_offset: number;
    /**
     * Max Level
     */
    max_level: number;
};

export type InfoProjectsProjectIdInfoGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/info';
};

export type InfoProjectsProjectIdInfoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InfoProjectsProjectIdInfoGetError = InfoProjectsProjectIdInfoGetErrors[keyof InfoProjectsProjectIdInfoGetErrors];

export type InfoProjectsProjectIdInfoGetResponses = {
    /**
     * Successful Response
     */
    200: WorldInfo;
};

export type InfoProjectsProjectIdInfoGetResponse = InfoProjectsProjectIdInfoGetResponses[keyof InfoProjectsProjectIdInfoGetResponses];

export type ServeTileProjectsProjectIdTilesZxyPngGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Z
         */
        z: number;
        /**
         * X
         */
        x: number;
        /**
         * Y
         */
        y: number;
    };
    query?: {
        sum_over?: SumOver;
        /**
         * Lp
         */
        lp?: Array<string> | null;
    };
    url: '/projects/{project_id}/tiles/{z}/{x}/{y}.png';
};

export type ServeTileProjectsProjectIdTilesZxyPngGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ServeTileProjectsProjectIdTilesZxyPngGetError = ServeTileProjectsProjectIdTilesZxyPngGetErrors[keyof ServeTileProjectsProjectIdTilesZxyPngGetErrors];

export type ServeTileProjectsProjectIdTilesZxyPngGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConfusionMatrixProjectsProjectIdConfusionMatrixGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * X Min
         */
        x_min: number;
        /**
         * Y Min
         */
        y_min: number;
        /**
         * X Max
         */
        x_max: number;
        /**
         * Y Max
         */
        y_max: number;
        /**
         * Lp
         */
        lp?: Array<string> | null;
    };
    url: '/projects/{project_id}/confusion_matrix';
};

export type GetConfusionMatrixProjectsProjectIdConfusionMatrixGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConfusionMatrixProjectsProjectIdConfusionMatrixGetError = GetConfusionMatrixProjectsProjectIdConfusionMatrixGetErrors[keyof GetConfusionMatrixProjectsProjectIdConfusionMatrixGetErrors];

export type GetConfusionMatrixProjectsProjectIdConfusionMatrixGetResponses = {
    /**
     * Successful Response
     */
    200: ConfusionMatrixResponse;
};

export type GetConfusionMatrixProjectsProjectIdConfusionMatrixGetResponse = GetConfusionMatrixProjectsProjectIdConfusionMatrixGetResponses[keyof GetConfusionMatrixProjectsProjectIdConfusionMatrixGetResponses];

export type ListProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type ListProjectsProjectsGetResponses = {
    /**
     * Response List Projects Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectResponse>;
};

export type ListProjectsProjectsGetResponse = ListProjectsProjectsGetResponses[keyof ListProjectsProjectsGetResponses];

export type GetProjectProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type GetProjectProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectProjectsProjectIdGetError = GetProjectProjectsProjectIdGetErrors[keyof GetProjectProjectsProjectIdGetErrors];

export type GetProjectProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type GetProjectProjectsProjectIdGetResponse = GetProjectProjectsProjectIdGetResponses[keyof GetProjectProjectsProjectIdGetResponses];

export type UpdateProjectProjectsProjectIdPutData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Description
         */
        description?: string | null;
    };
    url: '/projects/{project_id}';
};

export type UpdateProjectProjectsProjectIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectProjectsProjectIdPutError = UpdateProjectProjectsProjectIdPutErrors[keyof UpdateProjectProjectsProjectIdPutErrors];

export type UpdateProjectProjectsProjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: ProjectResponse;
};

export type UpdateProjectProjectsProjectIdPutResponse = UpdateProjectProjectsProjectIdPutResponses[keyof UpdateProjectProjectsProjectIdPutResponses];

export type GetProjectStatsProjectsProjectIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/stats/';
};

export type GetProjectStatsProjectsProjectIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectStatsProjectsProjectIdStatsGetError = GetProjectStatsProjectsProjectIdStatsGetErrors[keyof GetProjectStatsProjectsProjectIdStatsGetErrors];

export type GetProjectStatsProjectsProjectIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectStatsResponse;
};

export type GetProjectStatsProjectsProjectIdStatsGetResponse = GetProjectStatsProjectsProjectIdStatsGetResponses[keyof GetProjectStatsProjectsProjectIdStatsGetResponses];

export type ListLabelClassesProjectsProjectIdLabelClassesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/label_classes/';
};

export type ListLabelClassesProjectsProjectIdLabelClassesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLabelClassesProjectsProjectIdLabelClassesGetError = ListLabelClassesProjectsProjectIdLabelClassesGetErrors[keyof ListLabelClassesProjectsProjectIdLabelClassesGetErrors];

export type ListLabelClassesProjectsProjectIdLabelClassesGetResponses = {
    /**
     * Response List Label Classes Projects  Project Id  Label Classes  Get
     *
     * Successful Response
     */
    200: Array<LabelClassResponse>;
};

export type ListLabelClassesProjectsProjectIdLabelClassesGetResponse = ListLabelClassesProjectsProjectIdLabelClassesGetResponses[keyof ListLabelClassesProjectsProjectIdLabelClassesGetResponses];

export type GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Label Class Id
         */
        label_class_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/label_classes/{label_class_id}';
};

export type GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetError = GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetErrors[keyof GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetErrors];

export type GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetResponses = {
    /**
     * Successful Response
     */
    200: LabelClassResponse;
};

export type GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetResponse = GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetResponses[keyof GetLabelClassProjectsProjectIdLabelClassesLabelClassIdGetResponses];

export type ListPatchesProjectsProjectIdPatchesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: {
        /**
         * Cursor
         *
         * Keyset cursor: last seen patch_id (exclusive lower bound)
         */
        cursor?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * X Min
         */
        x_min?: number | null;
        /**
         * Y Min
         */
        y_min?: number | null;
        /**
         * X Max
         */
        x_max?: number | null;
        /**
         * Y Max
         */
        y_max?: number | null;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
    };
    url: '/projects/{project_id}/patches/';
};

export type ListPatchesProjectsProjectIdPatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPatchesProjectsProjectIdPatchesGetError = ListPatchesProjectsProjectIdPatchesGetErrors[keyof ListPatchesProjectsProjectIdPatchesGetErrors];

export type ListPatchesProjectsProjectIdPatchesGetResponses = {
    /**
     * Response List Patches Projects  Project Id  Patches  Get
     *
     * Successful Response
     */
    200: Array<PatchResponse>;
};

export type ListPatchesProjectsProjectIdPatchesGetResponse = ListPatchesProjectsProjectIdPatchesGetResponses[keyof ListPatchesProjectsProjectIdPatchesGetResponses];

export type AssignLabelsByIdsProjectsProjectIdPatchesPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * Patch Ids
         *
         * Patch IDs to relabel
         */
        patch_ids: Array<number>;
        /**
         * Label Class Id
         *
         * Ground-truth label class to assign
         */
        label_class_id: number;
    };
    url: '/projects/{project_id}/patches/';
};

export type AssignLabelsByIdsProjectsProjectIdPatchesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignLabelsByIdsProjectsProjectIdPatchesPostError = AssignLabelsByIdsProjectsProjectIdPatchesPostErrors[keyof AssignLabelsByIdsProjectsProjectIdPatchesPostErrors];

export type AssignLabelsByIdsProjectsProjectIdPatchesPostResponses = {
    /**
     * Successful Response
     */
    200: LabelAssignResponse;
};

export type AssignLabelsByIdsProjectsProjectIdPatchesPostResponse = AssignLabelsByIdsProjectsProjectIdPatchesPostResponses[keyof AssignLabelsByIdsProjectsProjectIdPatchesPostResponses];

export type GetPatchProjectsProjectIdPatchesPatchIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Patch Id
         */
        patch_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/patches/{patch_id}';
};

export type GetPatchProjectsProjectIdPatchesPatchIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatchProjectsProjectIdPatchesPatchIdGetError = GetPatchProjectsProjectIdPatchesPatchIdGetErrors[keyof GetPatchProjectsProjectIdPatchesPatchIdGetErrors];

export type GetPatchProjectsProjectIdPatchesPatchIdGetResponses = {
    /**
     * Successful Response
     */
    200: PatchResponse;
};

export type GetPatchProjectsProjectIdPatchesPatchIdGetResponse = GetPatchProjectsProjectIdPatchesPatchIdGetResponses[keyof GetPatchProjectsProjectIdPatchesPatchIdGetResponses];

export type GetPatchImageProjectsProjectIdPatchesPatchIdImageGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Patch Id
         */
        patch_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/patches/{patch_id}/image';
};

export type GetPatchImageProjectsProjectIdPatchesPatchIdImageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatchImageProjectsProjectIdPatchesPatchIdImageGetError = GetPatchImageProjectsProjectIdPatchesPatchIdImageGetErrors[keyof GetPatchImageProjectsProjectIdPatchesPatchIdImageGetErrors];

export type GetPatchImageProjectsProjectIdPatchesPatchIdImageGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostData = {
    body: LabelAssignByPolygonRequest;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query: {
        /**
         * Label Class Id
         *
         * Ground-truth label class to assign
         */
        label_class_id: number;
        /**
         * Lp
         *
         * Label pair filter: repeat for each pair as 'gt,pred' (e.g. lp=0,1&lp=2,2)
         */
        lp?: Array<string> | null;
    };
    url: '/projects/{project_id}/patches/polygonassign';
};

export type AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostError = AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostErrors[keyof AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostErrors];

export type AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostResponses = {
    /**
     * Successful Response
     */
    200: LabelAssignResponse;
};

export type AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostResponse = AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostResponses[keyof AssignLabelsByPolygonProjectsProjectIdPatchesPolygonassignPostResponses];

export type ListSettingsProjectsProjectIdSettingsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/settings/';
};

export type ListSettingsProjectsProjectIdSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSettingsProjectsProjectIdSettingsGetError = ListSettingsProjectsProjectIdSettingsGetErrors[keyof ListSettingsProjectsProjectIdSettingsGetErrors];

export type ListSettingsProjectsProjectIdSettingsGetResponses = {
    /**
     * Response List Settings Projects  Project Id  Settings  Get
     *
     * Successful Response
     */
    200: Array<SettingResponse>;
};

export type ListSettingsProjectsProjectIdSettingsGetResponse = ListSettingsProjectsProjectIdSettingsGetResponses[keyof ListSettingsProjectsProjectIdSettingsGetResponses];

export type ListImagesProjectsProjectIdImagesGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/images/';
};

export type ListImagesProjectsProjectIdImagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListImagesProjectsProjectIdImagesGetError = ListImagesProjectsProjectIdImagesGetErrors[keyof ListImagesProjectsProjectIdImagesGetErrors];

export type ListImagesProjectsProjectIdImagesGetResponses = {
    /**
     * Response List Images Projects  Project Id  Images  Get
     *
     * Successful Response
     */
    200: Array<ImageResponse>;
};

export type ListImagesProjectsProjectIdImagesGetResponse = ListImagesProjectsProjectIdImagesGetResponses[keyof ListImagesProjectsProjectIdImagesGetResponses];

export type GetImageStatsProjectsProjectIdImagesImageIdStatsGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Image Id
         */
        image_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/images/{image_id}/stats/';
};

export type GetImageStatsProjectsProjectIdImagesImageIdStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageStatsProjectsProjectIdImagesImageIdStatsGetError = GetImageStatsProjectsProjectIdImagesImageIdStatsGetErrors[keyof GetImageStatsProjectsProjectIdImagesImageIdStatsGetErrors];

export type GetImageStatsProjectsProjectIdImagesImageIdStatsGetResponses = {
    /**
     * Successful Response
     */
    200: ImageStatsResponse;
};

export type GetImageStatsProjectsProjectIdImagesImageIdStatsGetResponse = GetImageStatsProjectsProjectIdImagesImageIdStatsGetResponses[keyof GetImageStatsProjectsProjectIdImagesImageIdStatsGetResponses];

export type GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Image Id
         */
        image_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/images/{image_id}/thumbnail/';
};

export type GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetError = GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetErrors[keyof GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetErrors];

export type GetImageThumbnailProjectsProjectIdImagesImageIdThumbnailGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExportPatchCsvData = {
    body: ExportRequest;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/export/patch-csv/';
};

export type ExportPatchCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportPatchCsvError = ExportPatchCsvErrors[keyof ExportPatchCsvErrors];

export type ExportPatchCsvResponses = {
    /**
     * Successful Response
     */
    200: ExportResponse;
};

export type ExportPatchCsvResponse = ExportPatchCsvResponses[keyof ExportPatchCsvResponses];

export type DownloadPatchCsvData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
        /**
         * Image Id
         */
        image_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/export/{session_id}/download/{image_id}';
};

export type DownloadPatchCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadPatchCsvError = DownloadPatchCsvErrors[keyof DownloadPatchCsvErrors];

export type DownloadPatchCsvResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OpenUploadSessionData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}/upload/open/';
};

export type OpenUploadSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenUploadSessionError = OpenUploadSessionErrors[keyof OpenUploadSessionErrors];

export type OpenUploadSessionResponses = {
    /**
     * Successful Response
     */
    200: OpenSessionResponse;
};

export type OpenUploadSessionResponse = OpenUploadSessionResponses[keyof OpenUploadSessionResponses];

export type UploadImagesData = {
    body: BodyUploadImages;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/images/';
};

export type UploadImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImagesError = UploadImagesErrors[keyof UploadImagesErrors];

export type UploadImagesResponses = {
    /**
     * Successful Response
     */
    200: UploadFilesResponse;
};

export type UploadImagesResponse = UploadImagesResponses[keyof UploadImagesResponses];

export type UploadMasksData = {
    body: BodyUploadMasks;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/masks/';
};

export type UploadMasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMasksError = UploadMasksErrors[keyof UploadMasksErrors];

export type UploadMasksResponses = {
    /**
     * Successful Response
     */
    200: UploadFilesResponse;
};

export type UploadMasksResponse = UploadMasksResponses[keyof UploadMasksResponses];

export type UploadPatchCsvData = {
    body: BodyUploadPatchCsv;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/patch_csv/';
};

export type UploadPatchCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadPatchCsvError = UploadPatchCsvErrors[keyof UploadPatchCsvErrors];

export type UploadPatchCsvResponses = {
    /**
     * Successful Response
     */
    200: UploadFilesResponse;
};

export type UploadPatchCsvResponse = UploadPatchCsvResponses[keyof UploadPatchCsvResponses];

export type ValidateUploadData = {
    body: ValidateRequest;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/validate/';
};

export type ValidateUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateUploadError = ValidateUploadErrors[keyof ValidateUploadErrors];

export type ValidateUploadResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateUploadResponse = ValidateUploadResponses[keyof ValidateUploadResponses];

export type ValidateUploadImageCsvData = {
    body: BodyValidateUploadImageCsv;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/validate/image-csv/';
};

export type ValidateUploadImageCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateUploadImageCsvError = ValidateUploadImageCsvErrors[keyof ValidateUploadImageCsvErrors];

export type ValidateUploadImageCsvResponses = {
    /**
     * Successful Response
     */
    200: ValidateResponse;
};

export type ValidateUploadImageCsvResponse = ValidateUploadImageCsvResponses[keyof ValidateUploadImageCsvResponses];

export type ProcessUploadData = {
    body: ProcessRequest;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/process/';
};

export type ProcessUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessUploadError = ProcessUploadErrors[keyof ProcessUploadErrors];

export type ProcessUploadResponses = {
    /**
     * Successful Response
     */
    200: ProcessResponse;
};

export type ProcessUploadResponse = ProcessUploadResponses[keyof ProcessUploadResponses];

export type ProcessUploadCsvData = {
    body: BodyProcessUploadCsv;
    path: {
        /**
         * Project Id
         */
        project_id: number;
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/projects/{project_id}/upload/{session_id}/process-csv/';
};

export type ProcessUploadCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessUploadCsvError = ProcessUploadCsvErrors[keyof ProcessUploadCsvErrors];

export type ProcessUploadCsvResponses = {
    /**
     * Successful Response
     */
    200: ProcessCsvResponse;
};

export type ProcessUploadCsvResponse = ProcessUploadCsvResponses[keyof ProcessUploadCsvResponses];

export type SearchRayTasksData = {
    /**
     * Ray Cluster Filters
     */
    body?: Array<Array<string>> | null;
    path?: never;
    query?: never;
    url: '/task';
};

export type SearchRayTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchRayTasksError = SearchRayTasksErrors[keyof SearchRayTasksErrors];

export type SearchRayTasksResponses = {
    /**
     * Response Searchraytasks
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SearchRayTasksResponse = SearchRayTasksResponses[keyof SearchRayTasksResponses];
