services:
  pg:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - "${PG_HOST_PORT}:5432"
    restart: unless-stopped
    networks:
      - default

  tsdb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - "${TSDB_HOST_PORT}:5432"
    restart: unless-stopped
    networks:
      - default

  ps:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    image: ps-prototype:latest
    depends_on:
      - pg
      - tsdb
    command:
      /bin/bash
    stdin_open: true
    tty: true
    # ports:
    #   - "8080:8080"
    networks:
      - default
    volumes:
      - ..:/opt/PatchSorter

networks:
  default: